### ISSUE TITLE
[BUG] HandleDir w/ DirOptions Cache.Enable serves malformed content

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1580]
## Summary

Serving files with `HandleDir`, `Dir` with the both Compress and Cache enabled causes malformed PNGs to be delivered.

## Reproduction
1. clone the sample code repository
2. `go build -o server main.go ; sudo ./server`
3. Try to load the app using Firefox, Chrome, etc.
4. Disable `Cache` and notice everything works

## Actual Behaviour
The images are malformed and the CSS is sometimes served as a corrupted binary.

The CSS comes into Firefox like so:
```css
���	n����a���body {
background-color: #000;
color: #fff;
}

h1 {
font-family: 'Source Code Pro', monospace;
}
�M1qVa���
```

## Expected Behaviour
The images and CSS should load correctly.

## Versions, etc
|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Sample Code
https://github.com/AlbinoGeek/iris-cache-issue
